/*
 RequireJS 2.1.12 Copyright (c) 2010-2014, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/jrburke/requirejs for details
*/
var requirejs,require,define;
(function(ba){function G(b){return"[object Function]"===K.call(b)}function H(b){return"[object Array]"===K.call(b)}function v(b,c){if(b){var d;for(d=0;d<b.length&&(!b[d]||!c(b[d],d,b));d+=1);}}function T(b,c){if(b){var d;for(d=b.length-1;-1<d&&(!b[d]||!c(b[d],d,b));d-=1);}}function t(b,c){return fa.call(b,c)}function l(b,c){return t(b,c)&&b[c]}function B(b,c){for(var d in b)if(t(b,d)&&c(b[d],d))break}function U(b,c,d,e){c&&B(c,function(c,f){if(d||!t(b,f))e&&"object"===typeof c&&c&&!H(c)&&!G(c)&&!(c instanceof
RegExp)?(b[f]||(b[f]={}),U(b[f],c,d,e)):b[f]=c});return b}function u(b,c){return function(){return c.apply(b,arguments)}}function ca(b){throw b;}function da(b){if(!b)return b;var c=ba;v(b.split("."),function(b){c=c[b]});return c}function C(b,c,d,e){c=Error(c+"\nhttp://requirejs.org/docs/errors.html#"+b);c.requireType=b;c.requireModules=e;d&&(c.originalError=d);return c}function ga(b){function c(a,m,b){var g,j,c,d,e,f,i,p,m=m&&m.split("/"),h=k.map,n=h&&h["*"];if(a){a=a.split("/");j=a.length-1;k.nodeIdCompat&&
Q.test(a[j])&&(a[j]=a[j].replace(Q,""));"."===a[0].charAt(0)&&m&&(j=m.slice(0,m.length-1),a=j.concat(a));j=a;for(c=0;c<j.length;c++)if(d=j[c],"."===d)j.splice(c,1),c-=1;else if(".."===d&&!(2>c||".."===j[c-1])&&0<c)j.splice(c-1,2),c-=2;a=a.join("/")}if(b&&h&&(m||n)){j=a.split("/");c=j.length;a:for(;0<c;c-=1){e=j.slice(0,c).join("/");if(m)for(d=m.length;0<d;d-=1)if(b=l(h,m.slice(0,d).join("/")))if(b=l(b,e)){g=b;f=c;break a}!i&&(n&&l(n,e))&&(i=l(n,e),p=c)}!g&&i&&(g=i,f=p);g&&(j.splice(0,f,g),a=j.join("/"))}return(g=
l(k.pkgs,a))?g:a}function d(a){z&&v(document.getElementsByTagName("script"),function(m){if(m.getAttribute("data-requiremodule")===a&&m.getAttribute("data-requirecontext")===i.contextName)return m.parentNode.removeChild(m),!0})}function e(a){var m=l(k.paths,a);if(m&&H(m)&&1<m.length)return m.shift(),i.require.undef(a),i.makeRequire(null,{skipMap:!0})([a]),!0}function n(a){var m,b=a?a.indexOf("!"):-1;-1<b&&(m=a.substring(0,b),a=a.substring(b+1,a.length));return[m,a]}function p(a,m,b,g){var j,d,e=null,
f=m?m.name:null,k=a,p=!0,h="";a||(p=!1,a="_@r"+(K+=1));a=n(a);e=a[0];a=a[1];e&&(e=c(e,f,g),d=l(r,e));a&&(e?h=d&&d.normalize?d.normalize(a,function(a){return c(a,f,g)}):c(a,f,g):(h=c(a,f,g),a=n(h),e=a[0],h=a[1],b=!0,j=i.nameToUrl(h)));b=e&&!d&&!b?"_unnormalized"+(O+=1):"";return{prefix:e,name:h,parentMap:m,unnormalized:!!b,url:j,originalName:k,isDefine:p,id:(e?e+"!"+h:h)+b}}function s(a){var m=a.id,b=l(h,m);b||(b=h[m]=new i.Module(a));return b}function q(a,b,c){var g=a.id,j=l(h,g);if(t(r,g)&&(!j||
j.defineEmitComplete))"defined"===b&&c(r[g]);else if(j=s(a),j.error&&"error"===b)c(j.error);else j.on(b,c)}function w(a,b){var c=a.requireModules,g=!1;if(b)b(a);else if(v(c,function(b){if(b=l(h,b))b.error=a,b.events.error&&(g=!0,b.emit("error",a))}),!g)f.onError(a)}function x(){R.length&&(ha.apply(A,[A.length,0].concat(R)),R=[])}function y(a){delete h[a];delete V[a]}function F(a,b,c){var g=a.map.id;a.error?a.emit("error",a.error):(b[g]=!0,v(a.depMaps,function(g,d){var e=g.id,f=l(h,e);f&&(!a.depMatched[d]&&
!c[e])&&(l(b,e)?(a.defineDep(d,r[e]),a.check()):F(f,b,c))}),c[g]=!0)}function D(){var a,b,c=(a=1E3*k.waitSeconds)&&i.startTime+a<(new Date).getTime(),g=[],j=[],f=!1,h=!0;if(!W){W=!0;B(V,function(a){var i=a.map,k=i.id;if(a.enabled&&(i.isDefine||j.push(a),!a.error))if(!a.inited&&c)e(k)?f=b=!0:(g.push(k),d(k));else if(!a.inited&&(a.fetched&&i.isDefine)&&(f=!0,!i.prefix))return h=!1});if(c&&g.length)return a=C("timeout","Load timeout for modules: "+g,null,g),a.contextName=i.contextName,w(a);h&&v(j,function(a){F(a,
{},{})});if((!c||b)&&f)if((z||ea)&&!X)X=setTimeout(function(){X=0;D()},50);W=!1}}function E(a){t(r,a[0])||s(p(a[0],null,!0)).init(a[1],a[2])}function I(a){var a=a.currentTarget||a.srcElement,b=i.onScriptLoad;a.detachEvent&&!Y?a.detachEvent("onreadystatechange",b):a.removeEventListener("load",b,!1);b=i.onScriptError;(!a.detachEvent||Y)&&a.removeEventListener("error",b,!1);return{node:a,id:a&&a.getAttribute("data-requiremodule")}}function J(){var a;for(x();A.length;){a=A.shift();if(null===a[0])return w(C("mismatch",
"Mismatched anonymous define() module: "+a[a.length-1]));E(a)}}var W,Z,i,L,X,k={waitSeconds:7,baseUrl:"./",paths:{},bundles:{},pkgs:{},shim:{},config:{}},h={},V={},$={},A=[],r={},S={},aa={},K=1,O=1;L={require:function(a){return a.require?a.require:a.require=i.makeRequire(a.map)},exports:function(a){a.usingExports=!0;if(a.map.isDefine)return a.exports?r[a.map.id]=a.exports:a.exports=r[a.map.id]={}},module:function(a){return a.module?a.module:a.module={id:a.map.id,uri:a.map.url,config:function(){return l(k.config,
a.map.id)||{}},exports:a.exports||(a.exports={})}}};Z=function(a){this.events=l($,a.id)||{};this.map=a;this.shim=l(k.shim,a.id);this.depExports=[];this.depMaps=[];this.depMatched=[];this.pluginMaps={};this.depCount=0};Z.prototype={init:function(a,b,c,g){g=g||{};if(!this.inited){this.factory=b;if(c)this.on("error",c);else this.events.error&&(c=u(this,function(a){this.emit("error",a)}));this.depMaps=a&&a.slice(0);this.errback=c;this.inited=!0;this.ignore=g.ignore;g.enabled||this.enabled?this.enable():
this.check()}},defineDep:function(a,b){this.depMatched[a]||(this.depMatched[a]=!0,this.depCount-=1,this.depExports[a]=b)},fetch:function(){if(!this.fetched){this.fetched=!0;i.startTime=(new Date).getTime();var a=this.map;if(this.shim)i.makeRequire(this.map,{enableBuildCallback:!0})(this.shim.deps||[],u(this,function(){return a.prefix?this.callPlugin():this.load()}));else return a.prefix?this.callPlugin():this.load()}},load:function(){var a=this.map.url;S[a]||(S[a]=!0,i.load(this.map.id,a))},check:function(){if(this.enabled&&
!this.enabling){var a,b,c=this.map.id;b=this.depExports;var g=this.exports,j=this.factory;if(this.inited)if(this.error)this.emit("error",this.error);else{if(!this.defining){this.defining=!0;if(1>this.depCount&&!this.defined){if(G(j)){if(this.events.error&&this.map.isDefine||f.onError!==ca)try{g=i.execCb(c,j,b,g)}catch(d){a=d}else g=i.execCb(c,j,b,g);this.map.isDefine&&void 0===g&&((b=this.module)?g=b.exports:this.usingExports&&(g=this.exports));if(a)return a.requireMap=this.map,a.requireModules=this.map.isDefine?
[this.map.id]:null,a.requireType=this.map.isDefine?"define":"require",w(this.error=a)}else g=j;this.exports=g;if(this.map.isDefine&&!this.ignore&&(r[c]=g,f.onResourceLoad))f.onResourceLoad(i,this.map,this.depMaps);y(c);this.defined=!0}this.defining=!1;this.defined&&!this.defineEmitted&&(this.defineEmitted=!0,this.emit("defined",this.exports),this.defineEmitComplete=!0)}}else this.fetch()}},callPlugin:function(){var a=this.map,b=a.id,d=p(a.prefix);this.depMaps.push(d);q(d,"defined",u(this,function(g){var j,
d;d=l(aa,this.map.id);var e=this.map.name,P=this.map.parentMap?this.map.parentMap.name:null,n=i.makeRequire(a.parentMap,{enableBuildCallback:!0});if(this.map.unnormalized){if(g.normalize&&(e=g.normalize(e,function(a){return c(a,P,!0)})||""),g=p(a.prefix+"!"+e,this.map.parentMap),q(g,"defined",u(this,function(a){this.init([],function(){return a},null,{enabled:!0,ignore:!0})})),d=l(h,g.id)){this.depMaps.push(g);if(this.events.error)d.on("error",u(this,function(a){this.emit("error",a)}));d.enable()}}else d?
(this.map.url=i.nameToUrl(d),this.load()):(j=u(this,function(a){this.init([],function(){return a},null,{enabled:!0})}),j.error=u(this,function(a){this.inited=!0;this.error=a;a.requireModules=[b];B(h,function(a){0===a.map.id.indexOf(b+"_unnormalized")&&y(a.map.id)});w(a)}),j.fromText=u(this,function(g,c){var d=a.name,e=p(d),P=M;c&&(g=c);P&&(M=!1);s(e);t(k.config,b)&&(k.config[d]=k.config[b]);try{f.exec(g)}catch(h){return w(C("fromtexteval","fromText eval for "+b+" failed: "+h,h,[b]))}P&&(M=!0);this.depMaps.push(e);
i.completeLoad(d);n([d],j)}),g.load(a.name,n,j,k))}));i.enable(d,this);this.pluginMaps[d.id]=d},enable:function(){V[this.map.id]=this;this.enabling=this.enabled=!0;v(this.depMaps,u(this,function(a,b){var c,g;if("string"===typeof a){a=p(a,this.map.isDefine?this.map:this.map.parentMap,!1,!this.skipMap);this.depMaps[b]=a;if(c=l(L,a.id)){this.depExports[b]=c(this);return}this.depCount+=1;q(a,"defined",u(this,function(a){this.defineDep(b,a);this.check()}));this.errback&&q(a,"error",u(this,this.errback))}c=
a.id;g=h[c];!t(L,c)&&(g&&!g.enabled)&&i.enable(a,this)}));B(this.pluginMaps,u(this,function(a){var b=l(h,a.id);b&&!b.enabled&&i.enable(a,this)}));this.enabling=!1;this.check()},on:function(a,b){var c=this.events[a];c||(c=this.events[a]=[]);c.push(b)},emit:function(a,b){v(this.events[a],function(a){a(b)});"error"===a&&delete this.events[a]}};i={config:k,contextName:b,registry:h,defined:r,urlFetched:S,defQueue:A,Module:Z,makeModuleMap:p,nextTick:f.nextTick,onError:w,configure:function(a){a.baseUrl&&
"/"!==a.baseUrl.charAt(a.baseUrl.length-1)&&(a.baseUrl+="/");var b=k.shim,c={paths:!0,bundles:!0,config:!0,map:!0};B(a,function(a,b){c[b]?(k[b]||(k[b]={}),U(k[b],a,!0,!0)):k[b]=a});a.bundles&&B(a.bundles,function(a,b){v(a,function(a){a!==b&&(aa[a]=b)})});a.shim&&(B(a.shim,function(a,c){H(a)&&(a={deps:a});if((a.exports||a.init)&&!a.exportsFn)a.exportsFn=i.makeShimExports(a);b[c]=a}),k.shim=b);a.packages&&v(a.packages,function(a){var b,a="string"===typeof a?{name:a}:a;b=a.name;a.location&&(k.paths[b]=
a.location);k.pkgs[b]=a.name+"/"+(a.main||"main").replace(ia,"").replace(Q,"")});B(h,function(a,b){!a.inited&&!a.map.unnormalized&&(a.map=p(b))});if(a.deps||a.callback)i.require(a.deps||[],a.callback)},makeShimExports:function(a){return function(){var b;a.init&&(b=a.init.apply(ba,arguments));return b||a.exports&&da(a.exports)}},makeRequire:function(a,e){function k(c,d,l){var n,q;e.enableBuildCallback&&(d&&G(d))&&(d.__requireJsBuild=!0);if("string"===typeof c){if(G(d))return w(C("requireargs","Invalid require call"),
l);if(a&&t(L,c))return L[c](h[a.id]);if(f.get)return f.get(i,c,a,k);n=p(c,a,!1,!0);n=n.id;return!t(r,n)?w(C("notloaded",'Module name "'+n+'" has not been loaded yet for context: '+b+(a?"":". Use require([])"))):r[n]}J();i.nextTick(function(){J();q=s(p(null,a));q.skipMap=e.skipMap;q.init(c,d,l,{enabled:!0});D()});return k}e=e||{};U(k,{isBrowser:z,toUrl:function(b){var d,e=b.lastIndexOf("."),f=b.split("/")[0];if(-1!==e&&(!("."===f||".."===f)||1<e))d=b.substring(e,b.length),b=b.substring(0,e);return i.nameToUrl(c(b,
a&&a.id,!0),d,!0)},defined:function(b){return t(r,p(b,a,!1,!0).id)},specified:function(b){b=p(b,a,!1,!0).id;return t(r,b)||t(h,b)}});a||(k.undef=function(b){x();var c=p(b,a,!0),e=l(h,b);d(b);delete r[b];delete S[c.url];delete $[b];T(A,function(a,c){a[0]===b&&A.splice(c,1)});e&&(e.events.defined&&($[b]=e.events),y(b))});return k},enable:function(a){l(h,a.id)&&s(a).enable()},completeLoad:function(a){var b,c,d=l(k.shim,a)||{},f=d.exports;for(x();A.length;){c=A.shift();if(null===c[0]){c[0]=a;if(b)break;
b=!0}else c[0]===a&&(b=!0);E(c)}c=l(h,a);if(!b&&!t(r,a)&&c&&!c.inited){if(k.enforceDefine&&(!f||!da(f)))return e(a)?void 0:w(C("nodefine","No define call for "+a,null,[a]));E([a,d.deps||[],d.exportsFn])}D()},nameToUrl:function(a,b,c){var d,e,h;(d=l(k.pkgs,a))&&(a=d);if(d=l(aa,a))return i.nameToUrl(d,b,c);if(f.jsExtRegExp.test(a))d=a+(b||"");else{d=k.paths;a=a.split("/");for(e=a.length;0<e;e-=1)if(h=a.slice(0,e).join("/"),h=l(d,h)){H(h)&&(h=h[0]);a.splice(0,e,h);break}d=a.join("/");d+=b||(/^data\:|\?/.test(d)||
c?"":".js");d=("/"===d.charAt(0)||d.match(/^[\w\+\.\-]+:/)?"":k.baseUrl)+d}return k.urlArgs?d+((-1===d.indexOf("?")?"?":"&")+k.urlArgs):d},load:function(a,b){f.load(i,a,b)},execCb:function(a,b,c,d){return b.apply(d,c)},onScriptLoad:function(a){if("load"===a.type||ja.test((a.currentTarget||a.srcElement).readyState))N=null,a=I(a),i.completeLoad(a.id)},onScriptError:function(a){var b=I(a);if(!e(b.id))return w(C("scripterror","Script error for: "+b.id,a,[b.id]))}};i.require=i.makeRequire();return i}var f,
x,y,D,I,E,N,J,s,O,ka=/(\/\*([\s\S]*?)\*\/|([^:]|^)\/\/(.*)$)/mg,la=/[^.]\s*require\s*\(\s*["']([^'"\s]+)["']\s*\)/g,Q=/\.js$/,ia=/^\.\//;x=Object.prototype;var K=x.toString,fa=x.hasOwnProperty,ha=Array.prototype.splice,z=!!("undefined"!==typeof window&&"undefined"!==typeof navigator&&window.document),ea=!z&&"undefined"!==typeof importScripts,ja=z&&"PLAYSTATION 3"===navigator.platform?/^complete$/:/^(complete|loaded)$/,Y="undefined"!==typeof opera&&"[object Opera]"===opera.toString(),F={},q={},R=[],
M=!1;if("undefined"===typeof define){if("undefined"!==typeof requirejs){if(G(requirejs))return;q=requirejs;requirejs=void 0}"undefined"!==typeof require&&!G(require)&&(q=require,require=void 0);f=requirejs=function(b,c,d,e){var n,p="_";!H(b)&&"string"!==typeof b&&(n=b,H(c)?(b=c,c=d,d=e):b=[]);n&&n.context&&(p=n.context);(e=l(F,p))||(e=F[p]=f.s.newContext(p));n&&e.configure(n);return e.require(b,c,d)};f.config=function(b){return f(b)};f.nextTick="undefined"!==typeof setTimeout?function(b){setTimeout(b,
4)}:function(b){b()};require||(require=f);f.version="2.1.12";f.jsExtRegExp=/^\/|:|\?|\.js$/;f.isBrowser=z;x=f.s={contexts:F,newContext:ga};f({});v(["toUrl","undef","defined","specified"],function(b){f[b]=function(){var c=F._;return c.require[b].apply(c,arguments)}});if(z&&(y=x.head=document.getElementsByTagName("head")[0],D=document.getElementsByTagName("base")[0]))y=x.head=D.parentNode;f.onError=ca;f.createNode=function(b){var c=b.xhtml?document.createElementNS("http://www.w3.org/1999/xhtml","html:script"):
document.createElement("script");c.type=b.scriptType||"text/javascript";c.charset="utf-8";c.async=!0;return c};f.load=function(b,c,d){var e=b&&b.config||{};if(z)return e=f.createNode(e,c,d),e.setAttribute("data-requirecontext",b.contextName),e.setAttribute("data-requiremodule",c),e.attachEvent&&!(e.attachEvent.toString&&0>e.attachEvent.toString().indexOf("[native code"))&&!Y?(M=!0,e.attachEvent("onreadystatechange",b.onScriptLoad)):(e.addEventListener("load",b.onScriptLoad,!1),e.addEventListener("error",
b.onScriptError,!1)),e.src=d,J=e,D?y.insertBefore(e,D):y.appendChild(e),J=null,e;if(ea)try{importScripts(d),b.completeLoad(c)}catch(l){b.onError(C("importscripts","importScripts failed for "+c+" at "+d,l,[c]))}};z&&!q.skipDataMain&&T(document.getElementsByTagName("script"),function(b){y||(y=b.parentNode);if(I=b.getAttribute("data-main"))return s=I,q.baseUrl||(E=s.split("/"),s=E.pop(),O=E.length?E.join("/")+"/":"./",q.baseUrl=O),s=s.replace(Q,""),f.jsExtRegExp.test(s)&&(s=I),q.deps=q.deps?q.deps.concat(s):
[s],!0});define=function(b,c,d){var e,f;"string"!==typeof b&&(d=c,c=b,b=null);H(c)||(d=c,c=null);!c&&G(d)&&(c=[],d.length&&(d.toString().replace(ka,"").replace(la,function(b,d){c.push(d)}),c=(1===d.length?["require"]:["require","exports","module"]).concat(c)));if(M){if(!(e=J))N&&"interactive"===N.readyState||T(document.getElementsByTagName("script"),function(b){if("interactive"===b.readyState)return N=b}),e=N;e&&(b||(b=e.getAttribute("data-requiremodule")),f=F[e.getAttribute("data-requirecontext")])}(f?
f.defQueue:R).push([b,c,d])};define.amd={jQuery:!0};f.exec=function(b){return eval(b)};f(q)}})(this);
